name: Terraform Apply
on:
  repository_dispatch:
    types: [terraform-plan-command]

defaults:
  run:
    working-directory: infra

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Terraform
      env:
            TERRAFORM_VERSION: "0.13.5"
      run: |
        tf_version=$TERRAFORM_VERSION
        wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
        unzip terraform_"$tf_version"_linux_amd64.zip
        sudo mv terraform /usr/local/bin/

    - name: Verify Terraform version
      run: terraform --version

    - name: Terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: terraform init -input=false

    - name: Terraform validation
      run: |
        terraform validate > validate.txt
        pwd

    - name: Upload Plan Artifact
      id: build-image-app
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: validate.txt

    - name: Update comment
      uses: peter-evans/create-or-update-comment@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN  }}
        repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
        comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
        body: |
          > Command | Description
          > ${{ steps.terraform-plan.outputs.name }}   

    # - name: Terraform apply
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #   run: terraform apply -auto-approve -input=false
