name: Slash Command Dispatch
on:
  issue_comment:
    types: [created]
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch slash command (example)
        uses: peter-evans/slash-command-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          reaction-token: ${{ secrets.PAT }}
          issue-type: pull-request
          commands: example
          dispatch-type: workflow
          repository: jesher/ecs-example