name: Slash Command Dispatch
on:
  issue_comment:
    types: [created]
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN  }}
          commands: |
            terraform-plan
            terraform-apply
            terraform-destroy
            create-demo
            help
          permission: admin
          issue-type: pull-request

